title: m6a.jp
email: takuya.mk96@gmail.com
baseurl: ''
url: 'https://m6a.jp'
twitter_username: mktakuya
github_username:  mktakuya

# Build settings
markdown: kramdown
theme: minima
permalink: '/:categories/:year/:title/'
plugins:
  - jekyll-feed
